### ISSUE TITLE
Touchscreen config

### ISSUE THREAD

**Issue by err4o4** [bishopdynamics/spotify-car-thing_debian_chroot#5]
Used config from this [comment](https://github.com/bishopdynamics/spotify-car-thing_debian_chroot/issues/4#issuecomment-1312560909).  Touch is located here: `/dev/input/event3`

Tried two drivers `evdev` and `libinput`

**Firstly lets try `evdev` driver**

```
/etc/X11/xorg.conf.d/

Section "InputDevice"
        Identifier "TouchScreen"
        Driver  "evdev"
        Option "Device" "/dev/input/event3"
EndSection
```

And Xorg logs

```
root@buildroot:/# grep -e "TouchScreen" /var/log/Xorg.0.log

[  3222.564] (**) |-->Input Device "TouchScreen"
[  3224.102] (II) Using input driver 'evdev' for 'TouchScreen'
[  3224.102] (**) TouchScreen: always reports core events
[  3224.102] (**) evdev: TouchScreen: Device: "/dev/input/event3"
[  3224.102] (--) evdev: TouchScreen: Vendor 0 Product 0
[  3224.102] (--) evdev: TouchScreen: Found absolute axes
[  3224.102] (--) evdev: TouchScreen: Found absolute multitouch axes
[  3224.102] (II) evdev: TouchScreen: No buttons found, faking one.
[  3224.102] (II) evdev: TouchScreen: Forcing relative x/y axes to exist.
[  3224.102] (II) evdev: TouchScreen: Configuring as mouse
[  3224.102] (**) evdev: TouchScreen: YAxisMapping: buttons 4 and 5
[  3224.102] (**) evdev: TouchScreen: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[  3224.102] (II) XINPUT: Adding extended input device "TouchScreen" (type: MOUSE, id 6)
[  3224.102] (II) evdev: TouchScreen: initialized for relative axes.
[  3224.102] (WW) evdev: TouchScreen: ignoring absolute axes.
[  3224.103] (**) TouchScreen: (accel) keeping acceleration scheme 1
[  3224.103] (**) TouchScreen: (accel) acceleration profile 0
[  3224.103] (**) TouchScreen: (accel) acceleration factor: 2.000
[  3224.103] (**) TouchScreen: (accel) acceleration threshold: 4
[  3230.881] (II) evdev: TouchScreen: Close
```

Here this two lines looks strange:

```
[  3224.102] (II) evdev: TouchScreen: initialized for relative axes.
[  3224.102] (WW) evdev: TouchScreen: ignoring absolute axes.
```

Tried to `set-mode` to `ABSOLUTE` with no luck 

```
root@buildroot:/# xinit /usr/bin/xinput set-mode 6 ABSOLUTE

X Error of failed request:  XI_BadMode (invalid Mode parameter)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  5 (X_SetDeviceMode)
  Mode id in failed request: 0x17
  Serial number of failed request:  19
  Current serial number in output stream:  19
```

Just for info. List `xinput` devices

```
root@buildroot:/# xinit /usr/bin/xinput list --long

⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
	Reporting 3 classes:
		Class originated from: 2. Type: XIButtonClass
		Buttons supported: 10
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" None None None
		Button state:
		Class originated from: 2. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 2. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative

⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
	Reporting 3 classes:
		Class originated from: 4. Type: XIButtonClass
		Buttons supported: 10
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" None None None
		Button state:
		Class originated from: 4. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 4. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative

⎜   ↳ TouchScreen                             	id=6	[slave  pointer  (2)]
	Reporting 3 classes:
		Class originated from: 6. Type: XIButtonClass
		Buttons supported: 5
		Button labels: "Button Unknown" "Button Unknown" "Button Unknown" "Button Wheel Up" "Button Wheel Down"
		Button state:
		Class originated from: 6. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative
		Class originated from: 6. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative

⎜   ↳ Rotary                                  	id=8	[slave  pointer  (2)]
	Reporting 5 classes:
		Class originated from: 8. Type: XIButtonClass
		Buttons supported: 7
		Button labels: "Button Unknown" "Button Unknown" "Button Unknown" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right"
		Button state:
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Wheel
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative
		Class originated from: 8. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 1.000000
		  flags: 0x0

⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
	Reporting 1 classes:
		Class originated from: 3. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 5. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Keyboard                                	id=7	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 7. Type: XIKeyClass
		Keycodes supported: 248
```

And `watch-props` for touch
```
root@buildroot:/# xinit /usr/bin/xinput watch-props 6

Device 'TouchScreen':
	Device Enabled (117):	1
	Coordinate Transformation Matrix (118):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (238):	0
	Device Accel Constant Deceleration (239):	1.000000
	Device Accel Adaptive Deceleration (240):	1.000000
	Device Accel Velocity Scaling (241):	10.000000
	Device Product ID (242):	0, 0
	Device Node (243):	"/dev/input/event3"
	Evdev Axis Inversion (244):	0, 0
	Evdev Axes Swap (246):	0
	Axis Labels (247):	"Rel X" (127), "Rel Y" (128)
	Button Labels (248):	"Button Unknown" (237), "Button Unknown" (237), "Button Unknown" (237), "Button Wheel Up" (123), "Button Wheel Down" (124)
	Evdev Scrolling Distance (249):	0, 0, 0
	Evdev Middle Button Emulation (250):	0
	Evdev Middle Button Timeout (251):	50
	Evdev Middle Button Button (252):	2
	Evdev Third Button Emulation (253):	0
	Evdev Third Button Emulation Timeout (254):	1000
	Evdev Third Button Emulation Button (255):	3
	Evdev Third Button Emulation Threshold (256):	20
	Evdev Wheel Emulation (257):	0
	Evdev Wheel Emulation Axes (258):	0, 0, 4, 5
	Evdev Wheel Emulation Inertia (259):	10
	Evdev Wheel Emulation Timeout (260):	200
	Evdev Wheel Emulation Button (261):	4
	Evdev Drag Lock Buttons (262):	0


```

**Here is `libinput` driver**

```
/etc/X11/xorg.conf.d/

Section "InputDevice"
        Identifier "TouchScreen"
        Driver  "libinput"
        Option "Device" "/dev/input/event3"
EndSection
```

```
root@buildroot:/# grep -e "TouchScreen" /var/log/Xorg.0.log

[  3808.959] (**) |-->Input Device "TouchScreen"
[  3810.210] (II) Using input driver 'libinput' for 'TouchScreen'
[  3810.210] (**) TouchScreen: always reports core events
[  3812.285] (EE) libinput: TouchScreen: Failed to create a device for /dev/input/event3
[  3812.285] (EE) PreInit returned 2 for "TouchScreen"
```

So `libinput` can't init properly. More interestingly `xinit /usr/bin/libinput list-devices` doesn't report any devices, but `xinit /usr/bin/libinput record /dev/input/event3` report events normally 

```
xinit /usr/bin/libinput record /dev/input/event3

Recording to 'stdout'.
version: 1
ndevices: 1
libinput:
  version: "1.16.4"
  git: "unknown"
system:
  os: "debian:11"
  kernel: "4.9.113"
  dmi: "unknown"
devices:
- node: /dev/input/event3
  evdev:
    # Name: tlsc6x_dbg
    # ID: bus 0x18 vendor 00 product 00 version 00
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 1 (EV_KEY)
    #   Event code 330 (BTN_TOUCH)
    # Event type 3 (EV_ABS)
    #   Event code 47 (ABS_MT_SLOT)
    #       Value           0
    #       Min             0
    #       Max             1
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 48 (ABS_MT_TOUCH_MAJOR)
    #       Value           0
    #       Min             0
    #       Max            15
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 50 (ABS_MT_WIDTH_MAJOR)
    #       Value           0
    #       Min             0
    #       Max            15
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 53 (ABS_MT_POSITION_X)
    #       Value           0
    #       Min             0
    #       Max           480
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 54 (ABS_MT_POSITION_Y)
    #       Value           0
    #       Min             0
    #       Max           800
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 57 (ABS_MT_TRACKING_ID)
    #       Value           0
    #       Min             0
    #       Max         65535
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 58 (ABS_MT_PRESSURE)
    #       Value           0
    #       Min             0
    #       Max           127
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    # Properties:
    #    Property 1 (INPUT_PROP_DIRECT)
    name: "tlsc6x_dbg"
    id: [24, 0, 0, 0]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      1: [330] # EV_KEY
      3: [47, 48, 50, 53, 54, 57, 58] # EV_ABS
    absinfo:
      47: [0, 1, 0, 0, 0]
      48: [0, 15, 0, 0, 0]
      50: [0, 15, 0, 0, 0]
      53: [0, 480, 0, 0, 0]
      54: [0, 800, 0, 0, 0]
      57: [0, 65535, 0, 0, 0]
      58: [0, 127, 0, 0, 0]
    properties: [1]
  udev:
    properties:
  quirks:
  events:
  - evdev:
    - [  0,      0,   3,  57,     126] # EV_ABS / ABS_MT_TRACKING_ID      126
  - evdev:
    - [  0,      0,   3,  53,     187] # EV_ABS / ABS_MT_POSITION_X       187 (+23)
    - [  0,      0,   3,  54,     217] # EV_ABS / ABS_MT_POSITION_Y       217 (-55)
    - [  0,      0,   3,  58,      13] # EV_ABS / ABS_MT_PRESSURE          13 (+13)
    - [  0,      0,   1, 330,       1] # EV_KEY / BTN_TOUCH                 1
    - [  0,      0,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  - evdev:
    - [  0,  20708,   3,  57,      -1] # EV_ABS / ABS_MT_TRACKING_ID       -1
    - [  0,  20708,   3,  58,       0] # EV_ABS / ABS_MT_PRESSURE           0 (-13)
    - [  0,  20708,   1, 330,       0] # EV_KEY / BTN_TOUCH                 0
    - [  0,  20708,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +20ms
                                     # Touch device in neutral state
```
